---
# tasks file for ansible-role-opensearch_dashboards

- name: "Include {{ ansible_os_family }}.yml"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Include install-{{ ansible_os_family }}.yml"
  include: "install-{{ ansible_os_family }}.yml"

- name: Create opensearch_dashboards_conf_file
  ansible.builtin.template:
    src: opensearch_dashboards.yml.j2
    dest: "{{ opensearch_dashboards_conf_file }}"
  notify: Restart opensearch_dashboards

- name: Ensure data directory is writable by opensearch_dashboards_user
  ansible.builtin.file:
    path: "{{ opensearch_dashboards_data_dir }}"
    mode: "0755"
    owner: "{{ opensearch_dashboards_user }}"
    group: "{{ opensearch_dashboards_group }}"
    state: directory

- name: Start opensearch_dashboards
  ansible.builtin.service:
    name: "{{ opensearch_dashboards_service }}"
    state: started

- name: Wait for opensearch_dashboards in task
  ansible.builtin.wait_for:
    host: "{{ opensearch_dashboards_bind_address }}"
    port: "{{ opensearch_dashboards_bind_port }}"
