---
# tasks file for ansible-role-opensearch_dashboards

- name: "Include {{ ansible_os_family }}.yml"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Include install-{{ ansible_os_family }}.yml"
  include: "install-{{ ansible_os_family }}.yml"

- name: Create opensearch_dashboards_conf_file
  ansible.builtin.template:
    src: opensearch_dashboards.yml.j2
    dest: "{{ opensearch_dashboards_conf_file }}"
  notify: Restart opensearch_dashboards

- name: Start opensearch_dashboards
  ansible.builtin.service:
    name: "{{ opensearch_dashboards_service }}"
    state: started
