---
# tasks file for ansible-role-opensearch_dashboards

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create log directory
  file:
    path: "{{ opensearch_dashboards_log_dir }}"
    mode: 0755
    owner: "{{ opensearch_dashboards_user }}"
    group: "{{ opensearch_dashboards_group }}"
    state: directory
  notify: Restart opensearch_dashboards

- name: Create db directory
  file:
    path: "{{ opensearch_dashboards_db_dir }}"
    mode: 0755
    owner: "{{ opensearch_dashboards_user }}"
    group: "{{ opensearch_dashboards_group }}"
    state: directory
  notify: Restart opensearch_dashboards

- name: Create opensearch_dashboards.conf
  template:
    src: opensearch_dashboards.conf.j2
    dest: "{{ opensearch_dashboards_conf_file }}"
    validate: echo %s
  notify: Restart opensearch_dashboards

- name: Start opensearch_dashboards
  service:
    name: "{{ opensearch_dashboards_service }}"
    enabled: true
    state: started
